In [2]:
import pandas as pd
import numpy as np
import torch

# Basic Torch

In [3]:
x = torch.arange(12, dtype=torch.float32)
x

tensor([ 0.,  1.,  2.,  3.,  4.,  5.,  6.,  7.,  8.,  9., 10., 11.])

In [4]:
x.numel()

12

In [5]:
x.shape

torch.Size([12])

In [6]:
x.reshape(3,4)

tensor([[ 0.,  1.,  2.,  3.],
        [ 4.,  5.,  6.,  7.],
        [ 8.,  9., 10., 11.]])

# Basic Models

In [13]:
class TinyModel(torch.nn.Module):

    def __init__(self):
        super(TinyModel, self).__init__()
        self.linear1 = torch.nn.Linear(100,200)
        self.activation = torch.nn.ReLU()
        self.linear2 = torch.nn.Linear(200,10)
        self.softmax = torch.nn.Softmax()


    def forward(self, x):
        x = self.linear1(x)
        x = self.activation(x)
        x = self.linear2(x)
        x = self.softmax(x)
        return x

tinymodel = TinyModel()

In [14]:
for param in tinymodel.parameters():
    print(param)

Parameter containing:
tensor([[-0.0972, -0.0833, -0.0983,  ..., -0.0519, -0.0410, -0.0499],
        [-0.0218, -0.0049, -0.0595,  ...,  0.0935, -0.0551,  0.0573],
        [-0.0312, -0.0028, -0.0481,  ..., -0.0994, -0.0108,  0.0202],
        ...,
        [-0.0916, -0.0232,  0.0560,  ..., -0.0131,  0.0760,  0.0813],
        [-0.0796,  0.0861,  0.0575,  ..., -0.0889,  0.0810,  0.0418],
        [ 0.0020, -0.0650, -0.0403,  ...,  0.0639, -0.0066, -0.0419]],
       requires_grad=True)
Parameter containing:
tensor([ 0.0439, -0.0848,  0.0391, -0.0723,  0.0371, -0.0551, -0.0248,  0.0969,
         0.0765,  0.0820,  0.0057, -0.0484,  0.0003,  0.0422, -0.0093, -0.0434,
        -0.0638, -0.0013, -0.0043,  0.0794,  0.0599,  0.0648,  0.0757,  0.0987,
        -0.0801, -0.0880, -0.0520,  0.0602, -0.0116, -0.0963, -0.0283, -0.0708,
         0.0517, -0.0940,  0.0721,  0.0321, -0.0806, -0.0123, -0.0389,  0.0085,
        -0.0340,  0.0133, -0.0301,  0.0483,  0.0543,  0.0701, -0.0457, -0.0182,
        -0.0138

In [22]:
def is_prime(n):
    for j in range(2,int(np.floor(np.sqrt(n)))+1):
        if n % j == 0:
            return False
    return True

#for n in range(1,10000):

print(is_prime(13))

is_prime(6)

    

True


False

In [24]:
import math
def is_prime_with_math(number):
    if number <= 1:
        return False
    if number <= 3:
        return True
    if number % 2 == 0 or number % 3 == 0:
        return False
    for i in range(5, int(math.sqrt(number)) + 1, 6):
        if number % i == 0 or number % (i + 2) == 0:
            return False
    return True

# Test the function
num = 13
if is_prime_with_math(num):
    print(f"{num} is a prime number.")
else:
    print(f"{num} is not a prime number.")

13 is a prime number.


In [20]:
int(np.floor(np.sqrt(13)))

3

In [29]:
for n in range(2,1000000):
    if is_prime_with_math(n) != is_prime(n):
        print(n)
        break

In [30]:
def digit_frequency(n):
    # Initialize an empty dictionary to store the frequency of each digit
    frequency_map = {}

    # While n is greater than 0
    while n > 0:
        # Extract the last digit of n
        digit = n % 10

        # If the digit is not already a key in frequency_map
        if digit not in frequency_map:
            # Add the digit to frequency_map with an initial value of 1
            frequency_map[digit] = 1
        else:
            # If the digit is already in frequency_map, increment its value by 1
            frequency_map[digit] += 1

        # Reduce n by removing the last digit
        n = n // 10

    # Return the frequency map
    return frequency_map

# Example usage
n = 12345
frequency_map = digit_frequency(n)
print(frequency_map)

{5: 1, 4: 1, 3: 1, 2: 1, 1: 1}


In [35]:
def create_staircase(nums):
  step = 1
  subsets = []
  while len(nums) != 0:
    if len(nums) >= step:
      subsets.append(nums[0:step])
      nums = nums[step:]
      step += 1
    else:
      return False
      
  return subsets

create_staircase([1,2,3,4,5])

False